.set LOCALID_LASS, 2
.set LOCALID_SILVER, 3

NewBarkTown_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, NewBarkTown_OnTransition
	map_script MAP_SCRIPT_ON_FRAME_TABLE, NewBarkTown_OnFrame
	map_script MAP_SCRIPT_ON_RESUME, SetTimeEncounters
	map_script MAP_SCRIPT_ON_LOAD, NewBarkTown_OnLoad
	.byte 0

NewBarkTown_OnLoad::
	setrespawn HEAL_LOCATION_NEW_BARK_TOWN
	end

NewBarkTown_OnFrame::
	map_script_2 VAR_NEWBARK_TOWN_STATE, 6, NewBarkTown_EventScript_ElmCallAfterLeague
	.2byte 0

NewBarkTown_EventScript_ElmCallAfterLeague::
	lock
	pokenavcall BlackthornCity_Text_ElmCall
	waitmessage
	delay 30
	setvar VAR_NEWBARK_TOWN_STATE, 7
	setvar VAR_NEWBARKTOWN_LABSTATE, 10
	release
	end

NewBarkTown_OnTransition::
	goto_if_eq VAR_NEWBARK_TOWN_STATE, 2, NewBarkTown_Set_TalkToElm
	goto_if_eq VAR_NEWBARK_TOWN_STATE, 4, NewBarkTown_Set_TalkToMom
	end

NewBarkTown_Set_TalkToElm::
	clearflag FLAG_HIDE_SILVER_NEWBARKTOWN
	setobjectxyperm LOCALID_LASS, 0, 11
	callnative SetTimeBasedEncounters
	end

NewBarkTown_Set_TalkToMom::
	setobjectxyperm LOCALID_LASS, 0, 11
	callnative SetTimeBasedEncounters
	end

NewBarkTown_EventScript_LabSign::
	msgbox NewBarkTown_Text_LabSign, MSGBOX_SIGN
	end

NewBarkTown_EventScript_TownSign::
	msgbox NewBarkTown_Text_Sign, MSGBOX_SIGN
	closemessage
	end

NewBarkTown_EventScript_VsSeekerMan::
	goto_if_set FLAG_HIDE_VS_SEEKER_NPC, Common_EventScript_End
	lock
	applymovement LOCALID_VS_SEEKER_MAN, Common_Movement_ExclamationMark
	waitmovement 0
	msgbox NewBarkTown_Text_VsSeekerMan, MSGBOX_DEFAULT
	closemessage
	giveitem ITEM_VS_SEEKER
	msgbox NewBarkTown_Text_VsSeekerMan2, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_VS_SEEKER_MAN, NewBarkTown_Movement_VsSeekerMan
	waitmovement 0
	removeobject LOCALID_VS_SEEKER_MAN
	setflag FLAG_HIDE_VS_SEEKER_NPC
	release
	end

Common_EventScript_End::
	end

NewBarkTown_EventScript_Lass::
	lock
	faceplayer
	goto_if_eq VAR_NEWBARK_TOWN_STATE, 2, NewBarkTown_EventScript_LassState2
	goto_if_eq VAR_NEWBARK_TOWN_STATE, 3, NewBarkTown_EventScript_LassState3
	goto_if_eq VAR_NEWBARK_TOWN_STATE, 4, NewBarkTown_EventScript_LassState4
	msgbox NewBarkTown_Text_LassState5, MSGBOX_DEFAULT
	closemessage
	release
	end
	
NewBarkTown_EventScript_LassState2::
	playse SE_PIN
	applymovement LOCALID_LASS, Common_Movement_ExclamationMark
	waitmovement 0
	faceplayer
	waitmovement 0
	msgbox NewBarkTown_Text_LassState2, MSGBOX_DEFAULT
	closemessage
	release
	end

NewBarkTown_EventScript_LassState3::
	msgbox NewBarkTown_Text_LassState3, MSGBOX_DEFAULT
	closemessage
	release
	end

NewBarkTown_EventScript_LassState4::
	playse SE_PIN
	applymovement LOCALID_LASS, Common_Movement_ExclamationMark
	waitmovement 0
	faceplayer
	waitmovement 0
	msgbox NewBarkTown_Text_LassState4, MSGBOX_DEFAULT
	closemessage
	release
	end

NewBarkTown_EventScript_Wooper::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_WOOPER, CRY_MODE_NORMAL
	msgbox NewBarkTown_Text_Wooper, MSGBOX_DEFAULT
	waitmoncry
	release
	end
	
NewBarkTown_EventScript_Growlithe::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_GROWLITHE, CRY_MODE_NORMAL
	msgbox NewBarkTown_Text_Growlithe, MSGBOX_DEFAULT
	waitmoncry
	release
	end
	
NewBarkTown_EventScript_Furfrou::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_FURFROU, CRY_MODE_NORMAL
	msgbox NewBarkTown_Text_Furfrou, MSGBOX_DEFAULT
	waitmoncry
	release
	end
	
NewBarkTown_EventScript_Yamper::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_YAMPER, CRY_MODE_NORMAL
	msgbox NewBarkTown_Text_Yamper, MSGBOX_DEFAULT
	waitmoncry
	release
	end
	
NewBarkTown_EventScript_Maschiff::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_MASCHIFF, CRY_MODE_NORMAL
	msgbox NewBarkTown_Text_Maschiff, MSGBOX_DEFAULT
	waitmoncry
	release
	end

NewBarkTown_EventScript_Houndour::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_HOUNDOUR, CRY_MODE_NORMAL
	msgbox NewBarkTown_Text_Houndour, MSGBOX_DEFAULT
	waitmoncry
	release
	end

NewBarkTown_EventScript_Dachsbun::
	lock
	faceplayer
	waitse
	playmoncry SPECIES_DACHSBUN, CRY_MODE_NORMAL
	msgbox NewBarkTown_Text_Dachsbun, MSGBOX_DEFAULT
	waitmoncry
	release
	end

NewBarkTown_EventScript_LeaveTrigger::
	lock
	call_if_eq VAR_NEWBARK_TOWN_STATE, 2, NewBarkTown_EventScript_LeaveTriggersState2
	call_if_eq VAR_NEWBARK_TOWN_STATE, 4, NewBarkTown_EventScript_LeaveTriggersState4
	applymovement OBJ_EVENT_ID_PLAYER, OldaleTown_Movement_PlayerStepBack
	waitmovement 0
	release
	end

NewBarkTown_EventScript_LeaveTriggersState2::
	playse SE_PIN
	applymovement LOCALID_LASS, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_LASS, NewBarkTown_Movement_FaceDown
	waitmovement 0
	msgbox NewBarkTown_Text_LassState2, MSGBOX_DEFAULT
	closemessage
	return

NewBarkTown_EventScript_LeaveTriggersState4::
	playse SE_PIN
	applymovement LOCALID_LASS, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_LASS, NewBarkTown_Movement_FaceDown
	waitmovement 0
	msgbox NewBarkTown_Text_LassState4, MSGBOX_DEFAULT
	closemessage
	return 



NewBarkTown_EventScript_FatMan::
	lock
	faceplayer
	goto_if_eq VAR_NEWBARK_TOWN_STATE, 2, NewBarkTown_EventScript_FatManState2
	msgbox NewBarkTown_Text_FatManState3, MSGBOX_DEFAULT
	closemessage
	release
	end

NewBarkTown_EventScript_FatManState2::
	msgbox NewBarkTown_Text_FatManState2, MSGBOX_DEFAULT
	closemessage
	release
	end

NewBarkTown_EventScript_Silver::
	lock
	msgbox NewBarkTown_Text_Silver1, MSGBOX_DEFAULT
	delay 60
	playse SE_PIN
	applymovement LOCALID_SILVER, Common_Movement_ExclamationMark
	faceplayer
	waitmovement 0
	msgbox NewBarkTown_Text_Silver2, MSGBOX_DEFAULT
	playse SE_BANG
	applymovement LOCALID_SILVER, NewBarkTown_Movement_SilverPushesPlayer
	applymovement OBJ_EVENT_ID_PLAYER, NewBarkTown_Movement_PlayerPushedBySilver
	waitmovement 0
	applymovement LOCALID_SILVER, Common_Movement_FaceOriginalDirection
	waitmovement 0
	waitmovement 0
	release
	end


NewBarkTown_EventScript_Door::
	msgbox NewBarkTown_Text_Door, MSGBOX_SIGN
	end

NewBarkTown_EventScript_TestMan1::
	givebp 4
	msgbox BattleFrontier_Text_ObtainedXBattlePoints, MSGBOX_GETPOINTS
	end

NewBarkTown_EventScript_TestMan2::
	setvar VAR_NEWBARK_TOWN_STATE, 4
	setflag FLAG_HIDE_MOMS_FRIEND
	setflag FLAG_ADVENTURE_STARTED
	setflag FLAG_HIDE_SILVER_NEWBARKTOWN
	end

NewBarkTown_EventScript_TestMan3::
	setvar VAR_NEWBARK_TOWN_STATE, 5
	
	clearflag FLAG_COMPLETED_AERODACTYL_PUZZLE
	clearflag FLAG_COMPLETED_HOOH_PUZZLE
	clearflag FLAG_COMPLETED_KABUTO_PUZZLE
	clearflag FLAG_COMPLETED_OMANYTE_PUZZLE
	end

NewBarkTown_Movement_SilverPushesPlayer:
	walk_fast_left
	walk_fast_left
	walk_fast_down
	face_down
	lock_facing_direction
	unlock_facing_direction
	walk_fast_up
	walk_fast_right
	walk_fast_right
	step_end


NewBarkTown_Movement_PlayerPushedBySilver:
	walk_fast_left
	face_up
	walk_fast_down
	face_up
	lock_facing_direction
	jump_2_down
	unlock_facing_direction
	face_down
	step_end

	
NewBarkTown_Movement_VsSeekerMan:
	walk_down
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	walk_left
	step_end

NewBarkTown_Movement_FaceDown:
	face_down
	step_end

NewBarkTown_Text_LabSign:
	.string "Professor Elm's Lab$"

NewBarkTown_Text_Door:
	.string "The door is locked.$"

NewBarkTown_Text_Wooper:
	.string "Wooper: Woooooop.$"

NewBarkTown_Text_Growlithe:
	.string "Growlithe: Gr-chee-argh!$"

NewBarkTown_Text_Furfrou:
	.string "Furfrou: Le woof!$"

NewBarkTown_Text_Yamper:
	.string "Yamper: Yamp!$"

NewBarkTown_Text_Maschiff:
	.string "Maschiff: Grrr… ruff!$"

NewBarkTown_Text_Houndour:
	.string "Houndour: Grvaah!$"

NewBarkTown_Text_Dachsbun:
	.string "Dachsbun: Ruff! Ruff-ruff!$"

NewBarkTown_Text_FatManState2:
	.string "Wow, your Pokégear is impressive!\n"
	.string "Did your mom get it for you?$"

NewBarkTown_Text_FatManState3:
	.string "Yo, {PLAYER}!\p"
	.string "I hear Prof. Elm discovered\n"
	.string "some new Pokémon.$"

NewBarkTown_Text_LassState2:
	.string "Wait, {PLAYER}!\p"
	.string "It's dangerous to go out\n"
	.string "without a Pokémon!\p"
	.string "Wild Pokémon jump out of the grass\n"
	.string "on the way to the next town.$"

NewBarkTown_Text_LassState3:
	.string "Oh! Your Pokémon is adorable!\n"
	.string "I wish I had one!$"

NewBarkTown_Text_LassState4:
	.string "Hi, {PLAYER}! Leaving again?\p"
	.string "You should tell your mom if\n"
	.string "you are leaving.$"

NewBarkTown_Text_LassState5:
	.string "Call your mom on your PokéGear\n"
	.string "to let her know how you're doing.$\p"

NewBarkTown_Text_Silver1:
	.string ". . .\p"
	.string "So this is the famous Elm\n"
	.string "Pokémon Lab…$"

NewBarkTown_Text_Silver2:
	.string "…What are you staring at?$"

NewBarkTown_Text_Sign:
	.string "New Bark Town\p"
	.string "The town where baby dogs are born.$"

NewBarkTown_EventScript_PlayersHouseMailbox::
	msgbox NewBarkTown_Text_PlayersHouse, MSGBOX_SIGN
	end

NewBarkTown_EventScript_ElmsHouseMailbox::
	msgbox NewBarkTown_Text_ElmsHouse, MSGBOX_SIGN
	end

NewBarkTown_Text_PlayersHouse:
	.string "{PLAYER}'s House$"

NewBarkTown_Text_ElmsHouse:
	.string "Professor Elm's House$"

NewBarkTown_Text_VsSeekerMan:
	.string "Before you go, take this!$"

NewBarkTown_Text_VsSeekerMan2:
	.string "The VS. SEEKER allows you to\n"
	.string "battle trainers you have already\l"
	.string "battled before.\p"
	.string "You can use it to help train your\n"
	.string "POKéMON to the elite level!$"