FuchsiaCity_House1_MapScripts::
	.byte 0

FuchsiaCity_House1_EventScript_BillsOlderSister::
	msgbox FuchsiaCity_House1_Text_BillsOlderSister, MSGBOX_NPC
	end

FuchsiaCity_House1_EventScript_Youngster::
	msgbox FuchsiaCity_House1_Text_Youngster, MSGBOX_NPC
	end

FuchsiaCity_House1_Text_BillsOlderSister:
	.string "My grandpa is at my brother Bill's\n"
	.string "on Cerulean Cape.$"

FuchsiaCity_House1_Text_Youngster:
	.string "I saw these weird, slow Pokémon on\n"
	.string "Cycling Road.$"

