gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is OAK.\p"
	.string "People call me the Pokémon\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "People and Pokémon live together,\n"
	.string "by supporting each other.\p"
	.string "Some people play with Pokémon,\n"
	.string "some battle with them. \p"
	.string "But we don't know everything about\n"
	.string "Pokémon yet. \p"
	.string "There are still many mysteries\n"
	.string "to solve. That's why I study\l"
	.string "Pokémon every day.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "{PLAYER}{KUN}, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "You'll face fun times and tough\n"
	.string "challenges.\p"
	.string "A world of dreams and adventures\n"
	.string "with Pokémon awaits! Let's go!\p"
	.string "I'll be seeing you later!\p"
	.string "$"

gText_Birch_NuzlockeChallenge::
	.string "Oh, before we begin…\n"
	.string "There’s something new I’ve been\l"
	.string "researching.\p"
	.string "It’s called the NUZLOCKE CHALLENGE!\p"
	.string "It’s a special way to journey that\n"
	.string "makes your adventure more difficult\l"
	.string "and more meaningful.\p"
	.string "Under these rules, if one of your\n"
	.string "Pokémon faints, it’s considered unable\l"
	.string "to battle and must be released.\p"
	.string "Also, you may only catch the first\n"
	.string "Pokémon you encounter in each area.\p"
	.string "These rules test a TRAINER’S bond\n"
	.string "with their team.\p"
	.string "Every choice matters!\p"
	.string "So, would you like to play the\n"
	.string "NUZLOCKE CHALLENGE?\p"
	.string "$"

gText_Birch_NoNuzlocke::
	.string "That’s quite all right!\p"
	.string "There’s no shame in taking your\n"
	.string "journey at your own pace.\p"
	.string "I’ll leave the NUZLOCKE CHALLENGE\n"
	.string "disabled.\p"
	.string "If you decide you want to take on\n"
	.string "the challenge, you'll need to start\l"
	.string "a new game.\p"
	.string "$"

gText_Birch_YesNuzlocke::
	.string "I see!\n"
	.string "You’re looking for a real challenge!\p"
	.string "I’ll enable the NUZLOCKE CHALLENGE\n"
	.string "for your adventure.\p"
	.string "Take good care of your Pokémon.\n"
	.string "Every one of them will be important!\p"
	.string "$"

gText_Birch_Farewell::
	.string "You'll face fun times and tough\n"
	.string "challenges.\p"
	.string "A world of dreams and adventures\n"
	.string "with Pokémon awaits! Let's go!\p"
	.string "I'll be seeing you later!\p"
	.string "$"

gText_Birch_Difficulty::
	.string "Aha…\p"
	.string "And… How do you think this\n"
	.string "adventure is going to be?$"

gText_Birch_LockDifficulty::
	.string "If you need to change the DIFFICULTY\n"
	.string "you can open the OPTIONS MENU and\l"
	.string "change it from there.\p"
	.string "You can also lock it, if you want.\n"
	.string "Do you want to lock the\l"
	.string "chosen DIFFICULTY?\p"
	.string "This cannot be changed later.$"

gText_Birch_Challenge::
	.string "Oh, is that so?\p"
	.string "All right, with that clear…\n"
	.string "Do you expect any CHALLENGE\l"
	.string "in your journey?\p"
	.string "And what's your name?$"