Route26_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route26_OnTransition
	map_script MAP_SCRIPT_ON_RESUME, SetTimeEncounters
	.byte 0

Route26_OnTransition: 
	callnative SetTimeBasedEncounters
	end

Route26_EventScript_Jake::
	trainerbattle_single TRAINER_JAKE Route26_Text_CooltrainermJakeSeen, Route26_Text_CooltrainermJakeBeaten
	msgbox Route26_Text_CooltrainermJakeAfter, MSGBOX_AUTOCLOSE
	end

Route26_EventScript_Gaven::
	trainerbattle_single TRAINER_GAVEN Route26_Text_CooltrainermGavenSeen, Route26_Text_CooltrainermGavenBeaten
	msgbox Route26_Text_CooltrainermGavenAfter, MSGBOX_AUTOCLOSE
	end

Route26_EventScript_Joyce::
	trainerbattle_single TRAINER_JOYCE Route26_Text_CooltrainerfJoyceSeen, Route26_Text_CooltrainerfJoyceBeaten
	msgbox Route26_Text_CooltrainerfJoyceAfter, MSGBOX_AUTOCLOSE
	end

Route26_EventScript_Beth::
	trainerbattle_single TRAINER_BETH Route26_Text_CooltrainerfBethSeen, Route26_Text_CooltrainerfBethBeaten
	msgbox Route26_Text_CooltrainerfBethAfter, MSGBOX_AUTOCLOSE
	end

Route26_EventScript_Richard::
	trainerbattle_single TRAINER_RICHARD Route26_Text_PsychicRichardSeen, Route26_Text_PsychicRichardBeaten
	msgbox Route26_Text_PsychicRichardAfter, MSGBOX_AUTOCLOSE
	end

Route26_Text_CooltrainermJakeSeen:
    .string "I'm making my final preparations\n"
    .string "for the Pokémon League.$"

Route26_Text_CooltrainermJakeBeaten:
    .string "I blew it!$"

Route26_Text_CooltrainermJakeAfter:
    .string "It's going to be tough to win at\n"
    .string "the League.\p"
    .string "I need to do some more training.\p"
    .string "I hear that the League's Elite\n"
    .string "Four are tougher than Gym Leaders.$"

Route26_Text_CooltrainermGavenSeen:
    .string "By experiencing tough battles, you\n"
    .string "gain power.$"

Route26_Text_CooltrainermGavenBeaten:
    .string "Gaah! Life is even tougher!$"

Route26_Text_CooltrainermGavenAfter:
    .string "To get to Pokémon League, you have\n"
    .string "to get through Victory Road.\p"
    .string "But Victory Road is tough.\p"
    .string "Practically nobody goes there!$"

Route26_Text_CooltrainerfJoyceSeen:
    .string "Since you've come this far,\n"
    .string "you must be good.\p"
    .string "I'm going to give this battle\n"
    .string "everything I've got!$"

Route26_Text_CooltrainerfJoyceBeaten:
    .string "No! I don't believe this!$"

Route26_Text_CooltrainerfJoyceAfter:
    .string "I've defeated eight Gym Leaders,\n"
    .string "so I was feeling confident.\p"
    .string "I'll have to try harder next time.$"

Route26_Text_CooltrainerfBethSeen:
    .string "I lost to a trainer named Silver.\p"
    .string "He was really strong, but…\p"
    .string "It was as if he absolutely had to\n"
    .string "win at any cost.\p"
    .string "I felt sorry for his Pokémon.$"

Route26_Text_CooltrainerfBethBeaten:
    .string "Pokémon aren't tools of war.$"

Route26_Text_CooltrainerfBethAfter:
    .string "Pokémon are in-valuable, lifelong\n"
    .string "partners.$"

Route26_Text_PsychicRichardSeen:
    .string "Wow, look at all those Badges!\n"
    .string "I'm impressed.\p"
    .string "But you're not satisfied by just\n"
    .string "collecting them, right?$"

Route26_Text_PsychicRichardBeaten:
    .string "Good battle!$"

Route26_Text_PsychicRichardAfter:
    .string "People and Pokémon grow from their\n"
    .string "experiences.\p"
    .string "Don't get lazy and complacent.$"

Route26_Text_Sign:
    .string "Route 26\p"
    .string "Pokémon League\n"
    .string "Reception Gate$"

