VermilionCity_House2_MapScripts::
	.byte 0

VermilionCity_House2_EventScript_PokefanF::
	msgbox VermilionCity_House2_Text_PokefanF, MSGBOX_NPC
	end

VermilionCity_House2_EventScript_Youngster::
	msgbox VermilionCity_House2_Text_Youngster, MSGBOX_NPC
	end

VermilionCity_House2_Text_PokefanF:
	.string "Do you know about the Magnet\n"
	.string "Train?\p"
	.string "It's a railway that goes to\n"
	.string "Goldenrod in Johto.$"

VermilionCity_House2_Text_Youngster:
	.string "I want to go to Saffron to see\n"
	.string "the Magnet Train.$"
