DragonsDen_UpperLevel_MapScripts::
	.byte 0

DragonsDen_UpperLevel_EventScript_Cooltrainer::
	msgbox DragonsDen_UpperLevel_Text_Cooltrainer, MSGBOX_AUTOCLOSE
	end

DragonsDen_UpperLevel_Text_Cooltrainer:
	.string "There be dragons.\p"
	.string "Up there.\p"
	.string "No, seriously!\p"
	.string "You'll need to beat the Champion before\n"
	.string "you get up there.\p"
	.string "They're wicked powerful!$"